apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: challenge-tp-condition
  description: Used in B2B environments, the Challenge block is a non-rendered
    block responsible for checking if a user is allowed to access the store's
    content.
  tags:
    - typescript
    - react:16
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/challenge-tp-condition
    vtex.com/platform-flow-id: Shopper#1,Merch#1
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: GQ499BJP
spec:
  system: store-framework-ui-apps
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
  subcomponentOf: store-framework
